import { Student } from './types/student';
import { useStudentState } from './hooks/useStudentState';
import { EditToolbar } from './components/EditToolbar';
import { ReportHeader } from './components/ReportHeader';
import { KPICards } from './components/KPICards';
import { ModuleProgress } from './components/ModuleProgress';
import { SkillsAssessment } from './components/SkillsAssessment';
import { BehaviorEvaluation } from './components/BehaviorEvaluation';
import { InstructorFeedback } from './components/InstructorFeedback';
import { ValidationBanner } from './components/ValidationBanner';
import { calculateStats } from './utils/calculations';
import { generateInstructorFeedback } from './utils/feedbackGenerator';
export function App() {
  const { student, setStudent, isEditMode, setIsEditMode, stats, actions } =
    useStudentState();
  const handleImport = (data: Student) => {
    // If the imported data has empty feedback or is a fresh import, generate it
    if (!data.feedback || data.feedback.trim() === '') {
      const freshStats = calculateStats(data);
      data.feedback = generateInstructorFeedback(data, freshStats);
    }
    data.generatedDate = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    setStudent(data);
  };

  return (
    <div className="min-h-screen bg-[#F8F7FF] font-sans pb-20 print:bg-white print:pb-0">
      <EditToolbar
        isEditMode={isEditMode}
        toggleEditMode={() => setIsEditMode(!isEditMode)}
        student={student}
        onImport={handleImport} />


      <main className="max-w-4xl mx-auto px-6 py-4 print:p-0 print:max-w-none print:w-full">
        {isEditMode && <ValidationBanner student={student} />}

        <div className="space-y-4 print:space-y-2">
          <ReportHeader
            student={student}
            isEditMode={isEditMode}
            onUpdate={actions.updateStudentField}
            overallCompletion={stats.overallCompletion} />

          <KPICards stats={stats} />

          <ModuleProgress
            modules={student.modules}
            isEditMode={isEditMode}
            actions={actions} />

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 print:gap-2">
            <SkillsAssessment
              skills={student.skills}
              isEditMode={isEditMode}
              onUpdate={actions.updateSkill} />

            <BehaviorEvaluation
              student={student}
              isEditMode={isEditMode}
              onUpdate={actions.updateStudentField} />
          </div>

          <InstructorFeedback
            student={student}
            stats={stats}
            isEditMode={isEditMode}
            onUpdate={actions.updateStudentField} />
        </div>

        <div className="fixed bottom-0 left-0 right-0 bg-[#F8F7FF]/80 backdrop-blur-sm py-4 print:static print:bg-transparent print:mt-8">
          <div className="text-center text-[10px] text-gray-400">
            Generated by{' '}
            <span className="font-bold text-purple-600">Algorithmics</span> Report
            System · {student.generatedDate} · Confidential Academic Document
          </div>
        </div>
      </main>
    </div>);

}